<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="GZ-QA-AutoTool" name="KWS.prepare.t15_04_23_09_46_47" tests="1" failures="0" timestamp="24 Apr 2015 04:48:11 GMT" time="75.676" errors="1">
  <testcase name="Impersonatevendortomyaccount" time="75.676" classname="KWS.prepare.t15_04_23_09_46_47">
    <error type="java.lang.AssertionError" message="TIME OUT!! 20 second(s) has passed,but did not find element [By.xpath: .//*[@id=&#039;ui-id-2&#039;]//li[1]/a] ">
      <![CDATA[java.lang.AssertionError: TIME OUT!! 20 second(s) has passed,but did not find element [By.xpath: .//*[@id='ui-id-2']//li[1]/a] 
	at org.testng.Assert.fail(Assert.java:94)
	at KWS.prepare.autoMan.getElement(autoMan.java:63)
	at KWS.prepare.testdata.readExcel(testdata.java:73)
	at KWS.prepare.t15_04_23_09_46_47.Impersonatevendortomyaccount(t15_04_23_09_46_47.java:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- Impersonatevendortomyaccount -->
</testsuite> <!-- KWS.prepare.t15_04_23_09_46_47 -->
